#!/bin/bash

# Take a *.job file generated by the beta compiler and extract information from it and link the executable.
# This is needed to allow linking an executable in an environment with an unsupported `ld` without changing
# the `beta` source. This is required for boot straping from the legacy binaries.
#
# Here is how you use it:
#
# boot/bin/linux/beta -p FILE.bet
# run-fixed-job.sh linux/FILE..job

if [ $# -eq 0 ]; then
    echo "Usage: $0 <job_file> [other linker options]"
    exit 1
fi

JOB_FILE=$1
shift

if [ ! -f "$JOB_FILE" ]; then
    echo "Error: Job file '$JOB_FILE' not found"
    exit 1
fi
 
# This feels like a hack, but does work.
BETARUN_V_OBJ="/root/beta/lib/linux/ErnstRun/betarun_v.o"

OBJS="$(sed -n 's/.*"\(.*\.o\)".*/\1/p' "$JOB_FILE" | paste -s -d' ')"
OUTPUT_FILE="$(sed -n 's/.*-o \([^ ]*\).*/\1/p' "$JOB_FILE")"
gcc -L/usr/X11R6/lib -dynamic-linker /lib/ld-linux.so.2 -dc -dp -Bstatic \
    -o $OUTPUT_FILE \
    $OBJS \
    $BETARUN_V_OBJ \
    -Bdynamic -export-dynamic -ldl -lm -lc "$@"

# Check the result
case $? in
0)
echo "Object program on file: $OUTPUT_FILE"
;;
*)
/bin/rm -f $OUTPUT_FILE
echo "Build failed"
esac